name: install go

on: 
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  pull-code:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
      - uses: actions/setup-go@v5
      - run: go version